### ISSUE TITLE
BUG FOUND

### ISSUE THREAD

**Issue by DmitryPustovit** [AKTSA/AKTSA.github.io#3]
OH NOOOOOOOO, Your broke something with the full screen JS code
![image](https://user-images.githubusercontent.com/7939440/33292991-3051f9d8-d399-11e7-9274-c508470a6230.png)

Note how the first page does not reach all the way down to the end of my browser screen, something that Full Screen JS is supposed to do.

**Comment by agnim25** [comment]
The first image has a height of 90vh, not 100.

**Comment by mt-xing** [comment]
The home page does not run off fullscreen.js and the hero image is not intended to reach all the way to the bottom. This design choice was intentional - the design from 2 years ago needed a separate text field telling people to scroll down. This way, the existence of additional content below the fold is implied by the bar peeking into the page. I'm marking this as resolved.
